name: Syyclops_BIM

on:
  #push:
  # branches:
  #  - main
  workflow_dispatch:
    inputs:
      Branch_Name:
        description: 'Please specify the branch to be compiled - eg: master'
        required: true
        default: main
        type: string
      User_Name:
        description: 'Please specify the triggerer name'
        required: true
        type: string

jobs:
  Clone:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
  Build:
    runs-on: [ self-hosted ]
    needs: Clone
    steps:
      - name: Build the Docker Compose
        run: |
          docker-compose build
          
